baseURL = 'http://noahprezant.com/'
languageCode = 'en-us'
title = "Noah Prezant"
theme = "hello-friend-ng"

#baseurl      = "localhost"
#title        = "My Blog"
#languageCode = "en-us"
#theme        = "hello-friend-ng"
paginate     = 10

[params]
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Subtitle for home
homeSubtitle = "An amataur's collection of projects and lessons learned"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = false

# Metadata mostly used in document's head
description = "Noah Prezant blog"
keywords = "homepage, blog"
images = [""]

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[languages]
[languages.en]
title = "Welcome"
subtitle = "An amataur's collection of projects and lessons learned"
keywords = ""
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "Noah Prezant"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "blog"
name       = "Blog"
url        = "/posts"
