baseURL = 'http://noahprezant.com/'
languageCode = 'en-us'
title = "Noah Prezant"
theme = "bones"

# https://gohugo.io/content-management/menus/
[menu]
[[menu.main]]
  name = 'noah prezant'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'posts'
  pageRef = '/posts'
  weight = 20
[[menu.main]]
  name = 'about'
  pageRef = '/about'
  weight = 30

# To allow building restructured text
[security.exec]
  allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^rst2html$']

# Default home page config
[params]
  homeTitle = 'Welcome.'
  homeSubtitle = 'Feel free to poke around.'

# Taxonomies
[taxonomies]
  tag = 'tags'
